on: ["push", "pull_request"]
github-token: ${{ secrets.GITHUB_TOKEN }}
name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
